### ISSUE TITLE
Projection Lambert 72 (Belgium)

### ISSUE THREAD

**Issue by Pitbi** [vallettea/lambert-wilson#2]
Hi,

I need to convert WGS84 datas to the Belgian Lambert 72 projection. 
This module can help me? If yes, what parameters should I pass?

Thx.

**Comment by vallettea** [comment]
this packet is no longer maintained, use https://www.npmjs.com/package/proj4

**Comment by Pitbi** [comment]
Ok, that's what I did :)


Thx.
